### ISSUE TITLE
Installling

### ISSUE THREAD

**Issue by Bergschrat1** [yinflying/matlab-screen#2]
Hi,
noob here. 
As the Readme just says "The same as general plugin install steps." I just added 

`Plug 'yinflying/matlab-screen'`

in my init.vim and installed the Plugin via :PlugInstall.
What other steps do I have to do before I can use the plugin? Because when I use \mr in nvim right now I get
```
Error detected while processing function matlab#RunCell:
line    1:
E212: Can't open file for writing: permission denied
Error detected while processing function matlab#RunCell[3]..<SNR>29_matlab_log:
line    1:
E190: Cannot open "/home/user/Documents/Test/matlab_tmp.m" for writing
Error detected while processing function matlab#RunCell:
line    4:
E121: Undefined variable: s:matlab_buf
E116: Invalid arguments for function term_sendkeys
```

**Comment by yinflying** [comment]
vim 8.1 have the feature to open terminal in vim.... but I don't know how nvim to do so.
so it do not support nvim yet.

or you can use the vim7 branch which use `gnu screen` as carrrier to pass command to terminal. which maybe more tricks...

**Comment by Bergschrat1** [comment]
when I type \mr in vim 8.1 I just get:
```
Error detected while processing function matlab#RunCell:
line    4:
E121: Undefined variable: s:matlab_buf
E116: Invalid arguments for function term_sendkeys

```

**Comment by yinflying** [comment]
you need start matlab first. 
`<leader> mt `

NOTE:configure: the matlab run command(must be defined) 
```
    let g:matlab_term_cmd='matlab -nodesktop'
```

**Comment by Bergschrat1** [comment]
Thanks for the help. I got it working now. 
It turned out that my /usr/bin/matlab file did just contain the path to the real matlab executable and didn't allow startup options. So I replaced it with a symbolic link to the matlab executable.
